project:
  type: website
  output-dir: docs
  
website:
  title: "GenR website"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd     
      - projects.qmd
      - about.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Introduction"
        href: introduction.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source

