project:
  type: website
  output-dir: docs
  
website:
  title: "GenR website"
  navbar:
    left:
      - href: index.qmd  
        text: "Home"   
      - projects.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    toc: true


