on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'

      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Commit and push rendered files to gh-pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout --orphan gh-pages  # Create a new `gh-pages` branch or switch to it
          git add docs/*  # Stage the rendered files in the `docs/` directory
          git commit -m "Publish website to GitHub Pages"
          git push --force origin gh-pages  # Force push to `gh-pages` branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}